site_name: My Docs
site_url: https://wiki.joshualent.com
site_dir: "site"
site_author: Joshua Lent
site_description: >-
  My personal documentation on computer science, programming, and related subjects - Focus on web-development

repo_name: joshualent/joshisdev-docs
repo_url: https://github.com/joshualent/joshisdev-docs

copyright: Copyright &copy; 2025 Joshua Lent

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
