site_name: joshIsDev Docs
site_url: https://wiki.joshualent.com
site_dir: "site"
site_author: Joshua Lent
site_description: >-
  My personal documentation on computer science, programming, and related subjects - Focus on web-development

repo_name: joshualent/joshisdev-docs
repo_url: https://github.com/joshualent/joshisdev-docs

copyright: Made with ❤️ by Josh

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  features:
    - content.code.copy
    - content.code.select
nav:
  - Index: index.md
  - DevOps:
      - devops/git.md
      - devops/test.md
markdown_extensions:
  - def_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
